# Generated by Django 5.1.6 on 2025-03-06 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskmanager', '0002_task_description_task_priority_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mytaskmanager.task')),
            ],
            bases=('mytaskmanager.task',),
        ),
    ]
