# Generated by Django 5.1.6 on 2025-03-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskmanager', '0003_taskmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
