# Generated by Django 5.1.6 on 2025-03-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskmanager', '0004_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
