# Generated by Django 5.1.6 on 2025-03-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskmanager', '0006_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
